import * as yup from 'yup';

import {Field, FieldType} from '../../types/fields';

export const fields: Field[] = [
    {
        id: 'name',
        pathToValue: 'name',
        type: FieldType.TEXT,
        placeholder: 'Enter your name',
        defaultValue: null,
        require: true,
        checkIsFill: (val) => val !== '' &&  val !== null,
        validatorScheme: yup.string().matches(/[a-zA-Z]/, 'Please enter a valid name').required(),
    },
    {
        id: 'email',
        pathToValue: 'email',
        type: FieldType.TEXT,
        placeholder: 'Email',
        defaultValue: null,
        require: true,
        iconStartName: 'email',
        checkIsFill: (val) => val !== '' &&  val !== null,
        validatorScheme: yup.string().required().email(),
    },
    {
        id: 'password',
        pathToValue: 'password',
        type: FieldType.TEXT,
        nativeType: 'password',
        placeholder: 'Password',
        defaultValue: null,
        require: true,
        iconStartName: 'secure',
        checkIsFill: (val) => val !== '' &&  val !== null,
        validatorScheme: yup.string().min(6).required(),
    },
    {
        id: 'country',
        pathToValue: 'country',
        type: FieldType.SELECT,
        placeholder: 'Select country',
        dictionaryNameToOptions: 'countries',
        defaultValue: null,
        require: true,
        checkIsFill: (val) => val !== null,
        validatorScheme: yup.string().required(),
    },
    {
        id: 'gender',
        pathToValue: 'gender',
        type: FieldType.RADIO,
        nativeType: 'gender',
        defaultValue: null,
        require: true,
        options: [
            {
                id: 'm',
                label: 'Male',
            },
            {
                id: 'f',
                label: 'Female',
            },
        ],
        checkIsFill: (val) => val !== null,
        validatorScheme: yup.string().required(),
    },
    {
        id: 'consent',
        pathToValue: 'consent',
        type: FieldType.CHECKBOX,
        defaultValue: false,
        require: true,
        label: 'Accept <a href="#">terms</a> and <a href="#">conditions</a>',
        isLabelAsHtml: true,
        checkIsFill: (val) => val !== false,
        validatorScheme: yup.boolean().oneOf([true]).required(),
    },
];